'use client';

import { motion } from 'framer-motion';
import { Sparkles } from 'lucide-react';

interface BudgetCardProps {
  title: string;
  description: string;
  color: string;
  backgroundImage?: string;
  bottomImage?: string;
  generatedByPaige?: boolean;
  mockupTitle?: string;
}

export default function BudgetCard({ 
  title, 
  description, 
  color, 
  backgroundImage, 
  bottomImage,
  generatedByPaige = false,
  mockupTitle
}: BudgetCardProps) {
  const budgetData = {
    venue: "$8,500",
    catering: "$12,000", 
    allocated: "$23,700",
    flexibility: "$1,300"
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="group relative overflow-hidden rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-105 h-[28rem]"
      style={{ backgroundColor: color + '15' }}
    >
      {/* Background image */}
      {backgroundImage && (
        <div className="absolute inset-0 w-full h-full opacity-100 z-0">
          <img 
            src={backgroundImage} 
            alt={title} 
            className="w-full h-full object-cover"
          />
        </div>
      )}
      
      {/* Card Header */}
      <div className="p-6 pb-4 relative z-10">
        <h3 className="text-lg font-semibold text-gray-900 mb-3">
          {title}
        </h3>
        <p className="text-sm text-gray-600 leading-relaxed">
          {description}
        </p>
      </div>

      {/* Content Area */}
      <div className="px-6 pb-6 relative z-20">
        <div className={`flex justify-center items-start pt-0 ${bottomImage ? 'h-80' : 'h-96'}`}>
          <div className="bg-white rounded-xl p-4 shadow-lg w-[28rem] scale-[0.9] relative z-30">
            {generatedByPaige && (
              <div className="flex items-center justify-between mb-2">
                {mockupTitle && (
                  <div className="text-xs font-semibold text-[#5A4A42]">{mockupTitle}</div>
                )}
                <div className="flex items-center gap-1">
                  <Sparkles className="w-3 h-3 text-[#8B5CF6]" />
                  <span className="text-xs text-[#8B5CF6]">Generated by Paige</span>
                </div>
              </div>
            )}
            
            {/* Budget Content */}
            <div className="space-y-1 w-full">
              <div className="text-xs text-[#5A4A42]">Venue: {budgetData.venue}</div>
              <div className="text-xs text-[#5A4A42]">Catering: {budgetData.catering}</div>
              <div className="text-xs font-semibold text-[#5A4A42]">
                Tot. Allocated: {budgetData.allocated} | Flexibility: {budgetData.flexibility}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Image Container - only for budget */}
      {bottomImage && (
        <div className="absolute bottom-0 left-0 right-0 z-0">
          <img 
            src={bottomImage} 
            alt={title} 
            className="w-full h-48 object-cover rounded-b-2xl"
          />
        </div>
      )}
    </motion.div>
  );
}
