'use client';

import { useEffect, useState } from 'react';
import { Sparkles } from 'lucide-react';

export default function ScrollingTodoList() {
  const [isClient, setIsClient] = useState(false);

  // Prevent hydration mismatch
  useEffect(() => {
    setIsClient(true);
  }, []);

  // Scrolling to-do list effect
  useEffect(() => {
    if (!isClient) return;

    const handleScroll = () => {
      const todoContainer = document.getElementById('scrolling-todos');
      if (!todoContainer) return;

      const section = todoContainer.closest('section');
      if (!section) return;

      const rect = section.getBoundingClientRect();
      const windowHeight = window.innerHeight;
      
      // Calculate scroll progress (0 to 1)
      const scrollProgress = Math.max(0, Math.min(1, 
        (windowHeight - rect.top) / (windowHeight + rect.height)
      ));

      // Calculate how much to scroll the todo list (medium speed)
      const maxScroll = todoContainer.scrollHeight - todoContainer.parentElement!.offsetHeight;
      const scrollAmount = scrollProgress * maxScroll * 0.75; // 75% of normal speed for medium scroll

      todoContainer.style.transform = `translateY(-${scrollAmount}px)`;
    };

    window.addEventListener('scroll', handleScroll);
    handleScroll(); // Initial call

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, [isClient]);

  if (!isClient) {
    return null; // Prevent hydration mismatch
  }

  return (
    <div className="relative">
      {/* Background image container */}
      <div className="relative max-w-xs mx-0 lg:mx-0">
        <div 
          className="relative rounded-2xl overflow-hidden bg-cover bg-center bg-no-repeat aspect-square w-80 p-4 bg-white shadow-2xl shadow-black/20 scale-[0.65] lg:scale-100 -translate-x-6 lg:translate-x-0"
          style={{
            backgroundImage: 'url(/todocouple.png)'
          }}
        />
      </div>
      
      {/* Clean to-do list with drop shadow - overlapping the image */}
      <div className="absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-6 lg:translate-x-24 bg-white rounded-2xl shadow-lg shadow-black/10 w-72 lg:w-80 overflow-hidden z-10 scale-[0.65] lg:scale-100">
        {/* App header */}
        <div className="bg-[#A85C36] px-4 py-3">
          <div className="flex items-center justify-between">
            <h3 className="text-white font-semibold text-sm">Wedding To-Dos</h3>
            <div className="flex items-center gap-1">
              <Sparkles className="w-3 h-3 text-white/70" />
              <p className="text-white/70 text-xs">Generated by Paige</p>
            </div>
          </div>
        </div>
        
        {/* Scrolling to-do list */}
        <div className="px-4 py-4 h-56 overflow-hidden">
          <div className="transition-transform duration-100 ease-out" id="scrolling-todos">
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-[#A85C36] rounded-full flex items-center justify-center">
                  <div className="w-1.5 h-1.5 bg-[#A85C36] rounded-full"></div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Book photographer</div>
                  <div className="text-xs text-gray-500">Due: 3 months before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-[#A85C36] rounded-full flex items-center justify-center">
                  <div className="w-1.5 h-1.5 bg-[#A85C36] rounded-full"></div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-900 line-through opacity-60">Order wedding dress</div>
                  <div className="text-xs text-gray-500">Completed ✓</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-[#A85C36] rounded-full flex items-center justify-center">
                  <div className="w-1.5 h-1.5 bg-[#A85C36] rounded-full"></div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-900 line-through opacity-60">Send save the dates</div>
                  <div className="text-xs text-gray-500">Completed ✓</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Book venue</div>
                  <div className="text-xs text-gray-500">Due: 12 months before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-[#A85C36] rounded-full flex items-center justify-center">
                  <div className="w-1.5 h-1.5 bg-[#A85C36] rounded-full"></div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-900 line-through opacity-60">Book caterer</div>
                  <div className="text-xs text-gray-500">Completed ✓</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Order invitations</div>
                  <div className="text-xs text-gray-500">Due: 3 months before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Book florist</div>
                  <div className="text-xs text-gray-500">Due: 2 months before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Schedule hair & makeup trial</div>
                  <div className="text-xs text-gray-500">Due: 1 month before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Create seating chart</div>
                  <div className="text-xs text-gray-500">Due: 1 week before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Order wedding rings</div>
                  <div className="text-xs text-gray-500">Due: 2 months before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-[#A85C36] rounded-full flex items-center justify-center">
                  <div className="w-1.5 h-1.5 bg-[#A85C36] rounded-full"></div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-900 line-through opacity-60">Book DJ/Band</div>
                  <div className="text-xs text-gray-500">Completed ✓</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Plan honeymoon</div>
                  <div className="text-xs text-gray-500">Due: 6 months before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Choose wedding cake</div>
                  <div className="text-xs text-gray-500">Due: 3 months before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Book transportation</div>
                  <div className="text-xs text-gray-500">Due: 2 months before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4 border-b border-gray-200">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Finalize ceremony music</div>
                  <div className="text-xs text-gray-500">Due: 1 month before</div>
                </div>
              </div>
              
              <div className="flex items-center gap-3 py-4">
                <div className="w-4 h-4 border-2 border-gray-300 rounded-full"></div>
                <div>
                  <div className="text-sm font-medium text-gray-900">Pack for honeymoon</div>
                  <div className="text-xs text-gray-500">Due: 3 days before</div>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  );
}
