'use client';

import { useEffect, useState } from 'react';
import { Sparkles } from 'lucide-react';

export default function ScrollingTodoListReversed() {
  const [isClient, setIsClient] = useState(false);

  // Prevent hydration mismatch
  useEffect(() => {
    setIsClient(true);
  }, []);

  // Scrolling to-do list effect
  useEffect(() => {
    if (!isClient) return;

    const handleScroll = () => {
      const todoContainer = document.getElementById('scrolling-todos-reversed');
      if (!todoContainer) return;

      const section = todoContainer.closest('section');
      if (!section) return;

      const rect = section.getBoundingClientRect();
      const windowHeight = window.innerHeight;

      // Calculate scroll progress (0 to 1)
      const scrollProgress = Math.max(0, Math.min(1,
        (windowHeight - rect.top) / (windowHeight + rect.height)
      ));

      // Calculate how much to scroll the todo list (medium speed)
      const maxScroll = todoContainer.scrollHeight - todoContainer.parentElement!.offsetHeight;
      const scrollAmount = scrollProgress * maxScroll * 0.75; // Adjusted to 75% for medium speed

      todoContainer.style.transform = `translateY(-${scrollAmount}px)`;
    };

    window.addEventListener('scroll', handleScroll);
    handleScroll(); // Initial call

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, [isClient]);

  if (!isClient) {
    return null; // Prevent hydration mismatch
  }

  return (
    <div className="relative">
      {/* Clean to-do list with drop shadow - positioned on the left */}
      <div className="absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-[15rem] lg:-translate-x-[30rem] bg-white rounded-2xl shadow-lg shadow-black/10 w-80 lg:w-96 overflow-hidden z-10 scale-[0.65] lg:scale-100">
        {/* App header */}
        <div className="bg-[#805d93] px-4 py-3">
          <div className="flex items-center justify-between">
            <h3 className="text-white font-semibold text-sm">Email Draft</h3>
            <div className="flex items-center gap-1">
              <Sparkles className="w-3 h-3 text-white/70" />
              <p className="text-white/70 text-xs">Generated by Paige</p>
            </div>
          </div>
        </div>

        {/* Email draft content */}
        <div className="px-4 py-4 h-56 overflow-hidden flex items-center">
          <div className="transition-transform duration-100 ease-out w-full" id="scrolling-todos-reversed">
            {/* Email subject */}
            <div className="py-1">
              <div className="text-sm font-semibold text-gray-900">Wedding Photography Inquiry</div>
            </div>

            {/* Email body - continuous text */}
            <div className="py-1">
              <div className="text-sm text-gray-700 leading-relaxed">
                Hi Sarah! I hope this email finds you well. We're planning our wedding for June 15th, 2024 and would love to discuss your photography packages. Would you be available for a consultation next week?
              </div>
            </div>

            {/* Email status */}
            <div className="py-1">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 bg-orange-400 rounded-full"></div>
                <span className="text-xs text-gray-500">Draft • Ready to send</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Background image container - positioned on the right */}
      <div className="relative max-w-xs translate-x-8 lg:translate-x-0">
        <div
          className="relative rounded-2xl overflow-hidden bg-cover bg-center bg-no-repeat aspect-square w-80 p-4 bg-white shadow-2xl shadow-black/20 scale-[0.65] lg:scale-100"
          style={{
            backgroundImage: 'url(/photofinal.png)'
          }}
        />
      </div>
    </div>
  );
}
