import { OpenAI } from "openai";
import { NextResponse } from "next/server";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { weddingDate, template } = body;

    let prompt = "";
    if (template === "Day Of Tasks") {
      prompt = `Generate a list of tasks for a wedding day on ${weddingDate}. Include tasks like venue setup, catering, photography, etc.`;
    } else if (template === "General Wedding Tasks") {
      prompt = `Generate a list of general wedding planning tasks for a wedding on ${weddingDate}. Include tasks like venue booking, catering, invitations, etc.`;
    } else {
      prompt = `Generate a list of tasks for a wedding on ${weddingDate}. Include common tasks like venue booking, catering, invitations, etc.`;
    }

    const completion = await openai.chat.completions.create({
      model: "gpt-4",
      messages: [
        { role: "system", content: "You are a wedding planning assistant that generates structured task lists." },
        { role: "user", content: prompt }
      ],
      temperature: 0.7,
    });

    // Parse the AI response into a structured list of tasks
    const content = completion.choices[0].message.content;
    if (!content) {
      throw new Error("No content generated by OpenAI");
    }
    const tasks = content.split("\n").map((task: string) => ({
      name: task.trim(),
      note: "",
      category: "",
      deadline: null,
      endDate: null,
    }));

    return NextResponse.json({ listName: `Wedding Tasks for ${weddingDate}`, tasks });
  } catch (error: any) {
    console.error("Error in /api/generate-list:", error);
    return new NextResponse("Failed to generate list.", { status: 500 });
  }
} 